x-base: &base
  restart: unless-stopped
  network_mode: host
  volumes:
    - /dev/shm:/dev/shm
    - /tmp/iceoryx2:/tmp/iceoryx2

services:
  realsense_driver:
    <<: *base
    build:
      context: .
      dockerfile: nodes/realsense_driver/Dockerfile
    container_name: realsense_driver
    privileged: true
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/iceoryx2:/tmp/iceoryx2
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      - RS_CAMERA_INDEX=0
      - RS_WIDTH=1280
      - RS_HEIGHT=720
      - RS_FPS=30
      